require_relative 'bulk_data_test_kit/metadata.rb'
# frozen_string_literal: true
require_relative 'bulk_data_test_kit/metadata.rb'
require_relative 'inferno_requirements_tools/ext/inferno_core/runnable'
require_relative 'bulk_data_test_kit/metadata.rb'
require_relative 'bulk_data_test_kit/v1.0.1/bulk_data_test_suite'
require_relative 'bulk_data_test_kit/metadata.rb'
require_relative 'bulk_data_test_kit/v2.0.0/bulk_data_test_suite'
require_relative 'bulk_data_test_kit/metadata.rb'
require_relative 'bulk_data_test_kit/v2.0.0_client/bulk_data_client_test_suite'
